//  Usuarios
export const GET_RESOURCES_BY = "GET_RESOURCES_BY"
export const LOGIN = "LOGIN"
export const FETCH_RESOURCE = "FETCH_RESOURCE"
export const ADD_NOTIFICATION = "ADD_NOTIFICATION"
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION"